### ISSUE TITLE
[1.15.2] apparently there's an exception with loot tables but I'm not smart enough to know specifics

### ISSUE THREAD

**Issue by tlsctf2** [Zathrox/Explorercraft#44] opened 2020-12-29 11:59 UTC
According to diesieben07 on the Forge forums, the mod is using a deprecated method of modifying loot tables. I don't claim to know what they mean, admittedly, but [here's](https://forums.minecraftforge.net/topic/95696-1152-every-world-generated-chest-is-empty/) the thread with the information; it was initially asking about empty chests in world generation, but I was advised to let you know about this either way, so here I am.

**Comment by Zathrox** [comment] 2021-01-03 11:53
Thanks for bringing this to my attention, I thought i'd fixed or solved all those loottable bugs but they always creep up, i'm trying to work on the 1.16 port so i'll try and solve them there

**Comment by Zathrox** [comment] 2021-03-20 19:39
I have recently updated to 1.16, I shall hopefully have a new way of registering and injecting loot, so if this issue was caused by my mod, it should hopefully be resolved in later versions!

**Closed as completed by Zathrox** 2021-03-20 19:39 UTC
Labels: bug, 1.15.2, Resolved
